spring:  
  jpa:  
    hibernate:  
      ddl-auto: none  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/postgres"  
    username: postgres  
    password: root
  main:
    allow-circular-references: true     
springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs